### ISSUE TITLE
New version of CIS available

### ISSUE THREAD

**Issue by duncanwp** [cedadev/jasmin_scivm#35] opened 2015-10-04 19:27 UTC
The latest version of CIS is now 1.2. Could this be updated on the analysis VMs and in PyPI.

Also please note that the package has changed from 'jasmin-cis' to just 'cis' - sorry for any pain this might cause!

**Comment by alaniwi** [comment] 2015-10-09 07:23
Closing as duplicate of https://github.com/cedadev/jasmin_scivm/issues/33

**Closed by alaniwi** 2015-10-09 07:23 UTC
Labels: duplicate
